name: servidor
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  ansicolor: ^2.0.2
  pocketbase: ^0.18.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.25.2
